#PLAYBOOK
---
- name: Instalando o basico # Esta parte instala todos os serviços
  hosts: all
  remote_user: root
  become: true

  tasks:
    - name: update packages # Atualiza os pacotes da máquina
      become: true
      apt:
        update_cache: yes # Atualiza o cache

    - name: apt update # Atualiza informações dos pacotes
      apt: update_cache=yes
        force_apt_get=yes
        cache_valid_time=3600

    - name: apt upgrade # Atualiza os pacotes já instalados na máquina
      apt: upgrade=dist
        force_apt_get=yes
        force_apt_get=yes
        cache_valid_time=3600

    - name: install apache2 # Instala apache2
      become: true
      apt:
        name: apache2
        state: latest

    - name: install samba # Instala samba
      apt:
        name: ["samba"]
        state: latest

    - name: install squid3 # Instala squid3
      become: true
      apt:
        name: squid3
        state: latest

    - name: install postfix # Instala postfix
      become: true
      apt:
        name: postfix
        state: present

    - name: instala o mailutils # Instala mailutils
      become: true
      apt:
        name: mailutils
        state: present

    - name: instala o mutt # Instala mutt
      become: true
      apt:
        name: mutt
        state: present

    - name: install vsftpd # Instala vsftpd
      become: true
      apt:
        name: vsftpd
        state: present

    - name: install php # Instala php
      become: true
      apt:
        name: php
        state: present

#----------------------------------------------------------------------------------------------------------------------------------------------

- name: play 1 - samba # Realiza todas as configurações do samba
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: create admin group
      group:
        name: admin

    - name: create basic group
      group:
        name: basic

    - name: create admin user
      user: 
        name: adUser
        password: $6$Wy0bk8HBWEsZFKIQ$dCIArf.CsgaRi0.un8tWRAiemzPOBpJ6xCGoBO0MOSCTj81937lKivFRjd2Fcjo8pBNc3Zf/c9wSXuSZzkeNa.
        groups: admin

    - name: create basic user
      user: 
        name: baUser
        password: $6$WWgx4gjQP7WnljUY$ooRlAnGLc65sFJzx0dSeREowm7S5a8bzxRCfUxIvXcS1BdcIAYQwInTPLrX660PaFmHaj0BrrkIUdh6rIX.wO0
        groups: basic

    - name: create shared directory admin # Cria um diretório para ser compartilhado (admin)
      file:
        path: /home/vagrant/admin/
        state: directory
        mode: "0775"
        owner: "adUser"
        group: "admin"

    - name: create shared directory # Cria um diretório para ser compartilhado (basic)
      file:
        path: /home/vagrant/basic/
        state: directory
        mode: "0775"
        owner: "baUser"
        group: "basic"

    - name: send arquivoImportante.txt # Envia o arquivo para pasta
      copy:
        src: ./config/arquivoImportante.txt
        dest: /home/vagrant/admin/
        mode: "0766"
        owner: "adUser"
        group: "admin"

    - name: send arquivoImportante.txt # Envia o arquivo para pasta
      copy:
        src: ./config/arquivoImportante.txt
        dest: /home/vagrant/basic/
        mode: "0766"
        owner: "baUser"
        group: "basic"

    - name: add shared directory config # Enviando o arquivo de configuração do samba
      blockinfile:
        path: /etc/samba/smb.conf
        insertafter: EOF
        block: |
          [admin]
            path = /home/vagrant/admin
            browsable = yes
            valid users = @admin
            write list = @admin
            veto files = /*.exe/*.bin/*.csh/*.bat/*.ksh/*.out/*.run
          [basic]
            path = /home/vagrant/basic
            browsable = yes
            valid users = @admin @basic
            write list = @admin @basic
            veto files = /*.exe/*.bin/*.csh/*.bat/*.ksh/*.out/*.run
      notify: Reload Samba

    - name: set Samba passwords for each user # Setando a senha de todos usuários
      shell: "printf 'adUser\nadUser\n' | smbpasswd -a adUser"

    - name: set Samba passwords for each user # Setando a senha de todos usuários
      shell: "printf 'baUser\nbaUser\n' | smbpasswd -a baUser"

  handlers:
    - name: Reload Samba # Restarta o samba
      service:
        name: smbd
        state: restarted

    - name: reinicia o apache2 # Restarta o apache2
      service:
        name: apache2
        state: restarted

#----------------------------------------------------------------------------------------------------------------------------------------------

- name: play 2 - proxy # Realiza todas as configurações do proxy
  hosts: all
  remote_user: root
  become: true

  tasks:
    - name: move arquivo html # Move os arquivos do site (index.html)
      become: true
      copy:
        src: ./files/index.html
        dest: /var/www/html/index.html

    - name: move arquivo css # Move os arquivos do site (styles.css)
      become: true
      copy:
        src: ./files/styles.css
        dest: /var/www/html/styles.css

    - name: move arquivo javascript # Move os arquivos do site (app.js)
      become: true
      copy:
        src: ./files/app.js
        dest: /var/www/html/app.js

    - name: move arquivo squid config # Move o arquivo de configuração do proxy
      become: true
      copy:
        src: ./config/squid.conf
        dest: /etc/squid/squid.conf
        mode: "0777"
        owner: "vagrant"
        group: "vagrant"

    - name: move lista de sites bloqueados # Move o arquivo com os sites bloqueados
      become: true
      copy:
        src: ./config/denyWebsites.lst
        dest: /etc/squid/denyWebsites.lst

    - name: move lista de palavras bloqueados # Move o arquivo com as palavras bloqueados
      become: true
      copy:
        src: ./config/denyWords.lst
        dest: /etc/squid/denyWords.lst

    - name: reinicia o squid3 # Restarta o squid3
      service:
        name: squid
        state: restarted

    - name: reinicia o apache2 # Restarta o apache2
      service:
        name: apache2
        state: restarted

#----------------------------------------------------------------------------------------------------------------------------------------------

- name: play 3 - post mail # Realiza todas as configurações do postfix
  hosts: all
  remote_user: root
  become: true

  tasks:
    - name: move lista de extensoes bloqueadas # Move o arquivo com os extensoes bloqueadas
      become: true
      copy:
        src: ./config/files_extensions_check.lst
        dest: /etc/postfix/files_extensions_check.lst

    - name: add configs to postfix # Enviando o arquivo de configuração do postfix
      blockinfile:
        path: /etc/postfix/main.cf
        insertafter: EOF
        block: |
          header_checks = regexp:/etc/postfix/files_extensions_check.lst

    - name: adiciona configuracao de extensões # adiciona configuracao de extensões
      shell: postmap /etc/postfix/files_extensions_check.lst

    - name: limita o tamanho dos anexos em 10KB # limita o tamanho dos anexos em 10KB
      shell: postconf -e message_size_limit=10240

    - name: limita a quantidade de remetente # limita a quantidade de remetente
      shell: postconf -e smtpd_recipient_limit=2

    - name: starta o servico do postfix # Inicia o postfix
      become: true
      command: systemctl start postfix

#----------------------------------------------------------------------------------------------------------------------------------------------

- name: play 4 - Firewall # Realiza todas as configurações do Firewall
  hosts: all
  remote_user: root
  become: true

  tasks:
    - name: bloqueia todas as portas de entrada # bloqueia todas as portas de entrada
      shell: sudo ufw default deny incoming

    - name: bloqueia todas as portas de saida # bloqueia todas as portas de saida
      shell: sudo ufw default deny outgoing

    - name: permite conexoes FTP (porta 20) # Permite conexoes FTP (porta 20)
      shell: sudo ufw allow 20

    - name: permite conexoes FTP (porta 21) # Permite conexoes FTP (porta 21)
      shell: sudo ufw allow 21

    - name: bloqueia conexões por SSH # Bloqueia conexões por SSH
      shell: sudo ufw deny 22

    - name: permite conexões por TCP # Permite conexões por TCP
      shell: sudo ufw allow 23

    - name: permite conexoes SMTP # Permite conexoes SMTP
      shell: sudo ufw allow 25

    - name: permite conexoes DNS # Permite conexoes DNS
      shell: sudo ufw allow 53

    - name: permite acesso a porta 80 # Permite acesso à porta 80
      shell: sudo ufw allow 80

    - name: permite conexoes HTTPS # Permite conexoes HTTPS
      shell: sudo ufw allow 443

    - name: permite conexoes PROXY # Permite conexoes PROXY
      shell: sudo ufw allow 3128

    - name: permite conexoes MySQL # Permite conexoes MySQL
      shell: sudo ufw allow 3306

    - name: adiciona log para solicitações no Firewall # adiciona log para solicitações no Firewall
      shell: sudo ufw logging on high

    - name: Inicia o firewall # Inicia o firewall
      shell: sudo ufw enable

#----------------------------------------------------------------------------------------------------------------------------------------------

- name: play 5 - FTP # Realiza todas as configurações do FTP
  hosts: all
  remote_user: root
  become: true

  tasks:
    - name: starta o vsftpd # Inicia o vsftpd
      service:
        name: vsftpd
        state: started

    - name: move config file # Move o arquivo de configuração
      become: true
      copy:
        src: ./config/vsftpd.conf
        dest: /etc/vsftpd.conf

    - name: reinicia o vsftpd # Restarta o vsftpd
      service:
        name: vsftpd
        state: restarted

#----------------------------------------------------------------------------------------------------------------------------------------------
